import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name: "Amul White Limon Chocolate Bar",
    brand: "Amul",
    price: 80,
    originalPrice: 100,
    categoryName: "White Chocolate",
    rating: 4,
    image: "https://m.media-amazon.com/images/I/61-pg5u+9pL._SL1500_.jpg",
  },
  {
    _id: uuid(),
    name: "Nestle MILKYBAR Creamy White Chocolate",
    brand: "Nestle",
    price: 20,
    originalPrice: 35,
    categoryName: "White Chocolate",
    rating: 4.8,
    image: "https://m.media-amazon.com/images/I/61UHYRZQrZL._SL1500_.jpg",
  },
  {
    _id: uuid(),
    name: "Hershey's Kisses White Chocolates",
    brand: "Hershey's",
    price: 139,
    originalPrice: 165,
    categoryName: "White Chocolate",
    rating: 4.1,
    image: "https://m.media-amazon.com/images/I/61JjKHjetFL._SL1000_.jpg",
  },
  {
    _id: uuid(),
    name: "Cadbury Bournville Rich Cocoa 70% Dark Chocolate Bar",
    brand: "Cadbury",
    price: 91,
    originalPrice: 120,
    categoryName: "Dark Chocolate",
    rating: 3,
    image:
      "https://www.bigbasket.com/media/uploads/p/l/40191129-2_4-cadbury-bournville-rich-cocoa-70-dark-chocolate-bar.jpg",
  },
  {
    _id: uuid(),
    name: "Amul Sugar Free Dark Chocolate",
    brand: "Amul",
    price: 112,
    originalPrice: 120,
    categoryName: "Dark Chocolate",
    rating: 3.5,
    image: "https://m.media-amazon.com/images/I/81IBW9geZJL._SL1500_.jpg",
  },
  {
    _id: uuid(),
    name: "Amul Dark Chocolate",
    brand: "Amul",
    price: 109,
    originalPrice: 125,
    categoryName: "Dark Chocolate",
    rating: 2.9,
    image:
      "https://maplesfood.com/wp-content/uploads/2021/01/amul-dark-chocolate.jpg",
  },
  {
    _id: uuid(),
    name: "Amul Milk Chocolate",
    brand: "Amul",
    price: 74,
    originalPrice: 91,
    categoryName: "Milk Chocolate",
    rating: 4,
    image: "https://m.media-amazon.com/images/I/81Rz8SxtiJL._SL1500_.jpg",
  },
  {
    _id: uuid(),
    name: "Lindt Swiss Classic Milk Chocolate",
    brand: "Lindt",
    price: 74,
    originalPrice: 100,
    categoryName: "Milk Chocolate",
    rating: 3.9,
    image: "https://m.media-amazon.com/images/I/71EBaOPUs2L._SL1500_.jpg",
  },
  {
    _id: uuid(),
    name: "Cadbury Dairy Milk Chocolate Bar Family Pack",
    brand: "Cadbury",
    price: 96,
    originalPrice: 110,
    categoryName: "Milk Chocolate",
    rating: 3.8,
    image: "https://m.media-amazon.com/images/I/51odvWzqOQL._SL1000_.jpg",
  },
  {
    _id: uuid(),
    name: "Ruby Chocolate Bar Artisanté 70 Grams",
    brand: "Artisanté",
    price: 270,
    originalPrice: 300,
    categoryName: "Ruby Chocolate",
    rating: 3,
    image: "https://m.media-amazon.com/images/I/51Gj8QBId3L._SL1500_.jpg",
  },
];
